run:
  go: '1.19'

linters-settings:
  gofumpt:
    module-path: github.com/tamj0rd2/go-dots2
    extra-rules: true
linters:
  # Enable extra linters besides the default ones
  enable:
    - gofumpt
    - goconst
    - govet
    - stylecheck
    - unconvert
    - unparam
    - misspell
    - whitespace
    - bodyclose
